version: 1
disable_existing_loggers: true
formatters:
  db_formatter:
    format: "{asctime}: <{levelname}> - Модуль: <{filename}> - Функция: <{funcName}> - <{message}>"
    style: "{"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: db_formatter
  db_handler:
    class: logging.FileHandler
    filename: loggers/loggs.log
    formatter: db_formatter
loggers:
  db_logger:
    level: DEBUG
    handlers: [console]                # или db_handler
root:
  level: DEBUG
  handlers: [console,db_handler]
