version: 1
disable_existing_loggers: true
formatters:
  db_formatter:
    format: "{asctime}: <{levelname}> - Модуль: <{filename}> - Функция: <{funcName}> - <{message}>"
    style: "{"
handlers:
  db_handler:
    class: logging.FileHandler
    filename: loggers/logg.info
    formatter: db_formatter
loggers:
  db_logger:
    level: DEBUG
    handlers: [db_handler]